### ISSUE TITLE
Docker bump doesn't allow this to be installed

### ISSUE THREAD

**Issue by skarekrow** [OpenMediaVault-Plugin-Developers/openmediavault-docker-gui#84]
Seems upstream bumped `docker-ce` to `19.03.0~3-0~debian-stretch`

```
docker-ce:
  Installed: 5:19.03.0~3-0~debian-stretch
  Candidate: 5:19.03.0~3-0~debian-stretch
  Version table:
 *** 5:19.03.0~3-0~debian-stretch 500
        500 https://download.docker.com/linux/debian stretch/stable amd64 Packages
        100 /var/lib/dpkg/status
     5:18.09.8~3-0~debian-stretch 500
        500 https://download.docker.com/linux/debian stretch/stable amd64 Packages
```

` openmediavault-docker-gui : Depends: docker-ce (< 5:18.10) but 5:19.03.0~3-0~debian-stretch is to be installed` since it wants the older one

**Comment by ryecoaaron** [comment]
This isn't a bug.  We did this on purpose so that the plugin wouldn't break if the docker package changed.  As the output shows, a version that works with the plugin is still available.  You just happen to already have the latest version installed.

That said, I will test the new package with the plugin and release an updated version.

**Comment by skarekrow** [comment]
Sorry for the noise! Figured this just tracked the latest releases.

**Comment by ryecoaaron** [comment]
4.1.5 is in the repo.  This uses 19.03

**Comment by skarekrow** [comment]
Thanks @ryecoaaron 👍

**Comment by skarekrow** [comment]
Everything works nicely, thanks again :)
