### ISSUE TITLE
Compatibility with OMV5?

### ISSUE THREAD

**Issue by skluthe** [OpenMediaVault-Plugin-Developers/openmediavault-docker-gui#89]
Is there any way to get this installed on OMV5 or is it not available? I would like to follow some tutorials that use it and am unable to.

**Comment by ryecoaaron** [comment]
It will not work on OMV 5 and unless someone else maintains it, it will never be updated to work on OMV 5.  Portainer is what we are using on OMV5 because it has a large group of maintainers.  It isn't hard to translate what is being done on the OMV 4 plugin to Portainer.

https://forum.openmediavault.org/index.php?thread/24545-why-should-you-use-or-not-use-dockers/&postID=186122#post186122
